### ISSUE TITLE
Roadmap Discussions: Feedback & Ideas

### ISSUE THREAD

**Issue by tim-janik** [tim-janik/anklang#52]
This issue is a space for feedback and suggestions on the roadmap for the Anklang DAW project.

We welcome your thoughts on what features and improvements you would like to see in upcoming versions of Anklang.

Feel free to review the current roadmap and provide your input on what you would like to see changed or suggest new features that are not currently listed.

**Comment by Reaper10** [comment]
1. native window/ mac support or app 
2.  clip launcher 
live
![ableton-live-10-sessionview-1-770x425](https://github.com/tim-janik/anklang/assets/8137561/146cd394-2e96-49e6-ad97-10116d7eb58a)
bitwig
![Bitwig_ArrangePanel](https://github.com/tim-janik/anklang/assets/8137561/2a5be0d5-a3a7-4b23-8923-801169ba5f3a)
Ardor
![ardour-7-cue-clip-launcher](https://github.com/tim-janik/anklang/assets/8137561/c5860aae-4f30-4e9d-a5c6-5375d2b3d78a)
digital performer
![DP_1220_01-6MEFKKGBg2HA6wH8dh2kpYWJ94jj4RX3](https://github.com/tim-janik/anklang/assets/8137561/3e4f332a-50a2-4d0b-a0cb-c8e4a86daebb)

3. A way to Combined plugins into one like [Combinator](https://www.reasonstudios.com/en/reason/utilities/combinator) 
https://www.youtube.com/watch?v=O4VdwslQPGc&t=684s

4. [DSSI](https://dssi.sourceforge.net/) and [LADSPA](https://www.ladspa.org/) plugin support

**Comment by tim-janik** [comment]
> 1. native window/ mac support or app

This would require someone to volunteer to actually work on a port.
Considering signing requirements on modern proprietary OSes, this even has financial and liability impacts on developers. So ports will not make the roadmap until someone shows up who actively wants to work on that.

>     2. clip launcher

We have clips in a clip launcher already. When you run a recent Anklang, what actual features are you missing?


>     3. A way to Combined plugins into one like [Combinator](https://www.reasonstudios.com/en/reason/utilities/combinator)
>        https://www.youtube.com/watch?v=O4VdwslQPGc&t=684s

Have you looked at [CLAP#101](https://github.com/free-audio/clap/issues/101)? Is that what you are looking for?

>     4. [DSSI](https://dssi.sourceforge.net/) and [LADSPA](https://www.ladspa.org/) plugin support

There is LV2 support in the works (#32), is there anything in particular you can point at, the DSSI/LADSPA would enable, that is not yet covered by an LV2 plugin (or CLAP for that matter)?

**Comment by Reaper10** [comment]
> > 1. native window/ mac support or app
> 
> This would require someone to volunteer to actually work on a port. Considering signing requirements on modern proprietary OSes, this even has financial and liability impacts on developers. So ports will not make the roadmap until someone shows up who actively wants to work on that.
> 
> > ```
> > 2. clip launcher
> > ```
> 
> We have clips in a clip launcher already. When you run a recent Anklang, what actual features are you missing?
> 
> > ```
> > 3. A way to Combined plugins into one like [Combinator](https://www.reasonstudios.com/en/reason/utilities/combinator)
> >    https://www.youtube.com/watch?v=O4VdwslQPGc&t=684s
> > ```
> 
> Have you looked at [CLAP#101](https://github.com/free-audio/clap/issues/101)? Is that what you are looking for?
> 
> > ```
> > 4. [DSSI](https://dssi.sourceforge.net/) and [LADSPA](https://www.ladspa.org/) plugin support
> > ```
> 
> There is LV2 support in the works (#32), is there anything in particular you can point at, the DSSI/LADSPA would enable, that is not yet covered by an LV2 plugin (or CLAP for that matter)?

lofo grain are two ladspa that come to mind
![Screenshot_21-3-2024_12375_www ladspa org](https://github.com/tim-janik/anklang/assets/8137561/c84bca4a-8646-4710-b03e-397ab6ca5296)

![Screenshot_21-3-2024_12375_www ladspa org](https://github.com/tim-janik/anklang/assets/8137561/cba388a1-3a46-4184-b3d8-65ecfc281009)

fm synth/library compatible dx synth and [korg op 6](https://www.korg.com/us/products/synthesizers/opsix/) and[ op6 mk2](https://www.korg.com/us/products/synthesizers/opsix_mk2/)   you could stary [here](http://smbolton.com/hexter.html)

[grain sampler ](https://www.reasonstudios.com/devices/grain)
spectral synth like[ Izotope Iris ](https://www.youtube.com/watch?v=96C-5OifLcM&list=PL4dISychPQEvxteQUX1ZvbLSwGeF9EW-O) you could start [here](https://github.com/grz0zrg/fsynth/issues)

**Comment by swesterfeld** [comment]
Ideally @Reaper10 you would run Anklang, so that you could provide more fine grained feedback. As an example, for the **clip launcher** just saying "we need a clip launcher" is not a good small next step. We already have the basic UI for clips. Personally I would like to see - as some of the next steps:

 * ability to launch clips by mouse click
 * ability to stop clips by mouse click
 * ability to change duration of a clip (for instance be able to make 1-bar clips or 4-bar clips, currently all clips are 2-bar clips)

The **Windows/macOS port** is currently not too high on my personal priority list for Anklang, simply because I'd like to get more basic functionality implemented first. I've some experience in porting from SpectMorph/liquidsfz, so maybe I can work on a port later on. But if you want to run Anklang now, I'd recommend a virtual machine with Linux.

Finally as for **LADSPA/DSSI** I think if we want to make it into a next step, I'd recommend to make this

* support more plugin formats (VST2, VST3, LADSPA, DSSI) via Carla

The nice thing here is that Carla supports all these plugin formats, so we would only have to implement it once and get all of these. I think VST2/3 may even be more important than LADSPA/DSSI, simply because many proprietary DAWs use this.

**Comment by Reaper10** [comment]
> Ideally @Reaper10 you would run Anklang, so that you could provide more fine grained feedback. As an example, for the **clip launcher** just saying "we need a clip launcher" is not a good small next step. We already have the basic UI for clips. Personally I would like to see - as some of the next steps:
> 
> * ability to launch clips by mouse click
> * ability to stop clips by mouse click
> * ability to change duration of a clip (for instance be able to make 1-bar clips or 4-bar clips, currently all clips are 2-bar clips)
> 
> The **Windows/macOS port** is currently not too high on my personal priority list for Anklang, simply because I'd like to get more basic functionality implemented first. I've some experience in porting from SpectMorph/liquidsfz, so maybe I can work on a port later on. But if you want to run Anklang now, I'd recommend a virtual machine with Linux.
> 
> Finally as for **LADSPA/DSSI** I think if we want to make it into a next step, I'd recommend to make this
> 
> * support more plugin formats (VST2, VST3, LADSPA, DSSI) via Carla
> 
> The nice thing here is that Carla supports all these plugin formats, so we would only have to implement it once and get all of these. I think VST2/3 may even be more important than LADSPA/DSSI, simply because many proprietary DAWs use this.

i look though all info i could find i think you could use [CTLRA](https://github.com/openAVproductions/openAV-Ctlra) as the base for midi controller support.

**Comment by tim-janik** [comment]
> i look though all info i could find i think you could use [CTLRA](https://github.com/openAVproductions/openAV-Ctlra) as the base for midi controller support.

We already have MIDI controller support via the ALSA MIDI driver API. Take a look at the Preferences to select your MIDI device of interest.

**Note, running Anklang is a hard requirement for making useful contributions and discussion comments here.**

Come back when you are equipped to discuss the current ways Anklang operates, or when we can give you a hand getting Anklang to run on Linux.

**Comment by tim-janik** [comment]
Updates from today's meeting with @swesterfeld:

* [ ] TIMJ: Merge trkn branch and subdir into trunk
* [ ] TIMJ: Implement test sound generation and playback
* [ ] TIMJ: Add JACK audio support via trkn
* [ ] TIMJ: Implement project load and save functionality
* [ ] STW: Port liquidsfz to trkn
* [ ] TIMJ: Implement clip and MIDI note handling based on trkn
* [ ] TIMJ: Implement device property UIs for trkn
* [ ] STW: Implement file selection UI for liquidsfz
* [ ] STW: Port blepsynth to trkn
* [ ] TIMJ: Port remaining plugins to trkn
* [ ] TIMJ: Implement device editor (add/remove/trkn-devices)
* [ ] STW: Implement fluidsynth plugin for trkn (port from Beast?)
* [ ] TIMJ: Add sample downloader and sound library integration
* [ ] STW: Implement track properties (mute, solo, volume, panning)
* [ ] TIMJ: Implement Clip Launcher
* [ ] STW: Investigate and add automation support
* [ ] TIMJ: Implement telemetry-based audio visualizations
* [ ] STW: Add support for third-party plugins like LV2, VST
* [ ] TIMJ: Add MIDI file importer
* [ ] TIMJ: Maybe add other import/export format support
* [ ] TIMJ: Add audio track support (WAV via drag-and-drop)
* [ ] STW: Implement audio mixer
* [ ] TIMJ: Explore AI features

This is a tentative new roadmap, beginning with the integration of recent trkn developments into the trunk. Subsequent work will proceed in trunk, guided by the items listed, prioritized primarily based on interdependencies.

**Comment by swesterfeld** [comment]
> tentative new roadmap

This looks good for me as a basic first steps list of tasks. Indeed if we had all this, we had already a working project which could be used to make some music.

I am not sure how much the roadmap should go into detail for advanced features we may want to implement that are not on the list now. Here are a few examples, note that the concrete implmentation strategy we should use might be different from my brain storming here:

### LiquidSFZ and Drums

Right now, LiquidSFZ loads .sfz or hydrogen drumsets and plays drums and mixes the output down to one stereo output. This is ok for getting results quickly, but it would be better if we could apply effects on each drum individually (for instance less reverb to the base drum, more reverb to the snare drum). To get this it would be nice if we could get multiple stereo busses in the mixer. One way of doing this would be having multiple stereo outputs from LiquidSFZ which would need changes in both, LiquidSFZ and the trkn device. There are other possible implementations such as using one LiquidSFZ device per drum.

### Self Contained Save

Another LiquidSFZ related issue is that there should be the option to do self contained save. This should copy all files that are needed into the trkn project directory. Again this would need changes in both, LiquidSFZ and the trkn device. This could also be useful for the fluid synth trkn device. Since this could potentially include gigabytes of data, it should be optional.

It could also be smart in the sense that if samples have been downloaded using the integrated sample downloader, including them could be not default (but possible), as we would expect they can be downloaded again.

### BlepSynth, Modulation, LFOs

Another item (or multiple interrelated features) that is not on your list now is how to deal with modulation. Right now, the BlepSynth device doesn't include any LFO. So we cannot (as of now) make the waveform periodically change between saw and square (for example). We *could  theoretically* add one or more LFOs to the BlepSynth itself. However for maximum flexibility it would be nice if we implement the LFO independently of the BlepSynth device and just pass the modulated parameter to the BlepSynth. This may be difficult because as far as I know the trkn engine doesn't have modulation in that sense (only automation), at least not  per voice. Note that there are other modulators (such as envelopes or step sequencers) that we may want to implement.

As far as I know the 4OSC trkn device has internal LFOs.

CLAP plugins include the possibility for modulation (in addition to automation), but again trkn doesn't support CLAP yet.

### Presets and Chains

The trkn 4OSC includes effects like distortion, reverb and delay. This makes it possible to have these effects as part of the sound, and part of the preset. The BlepSynth currently does not include any effects. Again we *could theoretically* add effects to the BlepSynth. However, it would be nicer to have an effect chain that is part of the BlepSynth that can contain any effect. In that way it would be more flexible: combine any effect with BlepSynth and save as preset. It also allows controlling multiple parameters in the effects chain with one macro parameter that then can be automated.

Again chains are not part of the current design of the trkn engine, so it may be extra work to get this.

**Comment by tim-janik** [comment]
> > tentative new roadmap
> 
> This looks good for me as a basic first steps list of tasks.

Thanks for your comments. The roadmap updates are now in the README.md, would be happy to see you review it.
It is getting a bit long, so I wonder if it makes sense to move things into ROADMAP.md and maybe annotate the "phases" with Milestones instead. Could be useful, especially because your commentary above is more on the side of making roadmap items even more detailed, thoughts?

**Comment by swesterfeld** [comment]
> It is getting a bit long, so I wonder if it makes sense to move things into ROADMAP.md

I think it definitely makes sense to move it to ROADMAP.md, this is currently just cluttering up the main README.md too much for my taste. As I see it, README.md should be for users mostly, ROADMAP.md is more for developers.

**Comment by tim-janik** [comment]
> > It is getting a bit long, so I wonder if it makes sense to move things into ROADMAP.md
> 
> I think it definitely makes sense to move it to ROADMAP.md, this is currently just cluttering up the main README.md too much for my taste. As I see it, README.md should be for users mostly, ROADMAP.md is more for developers.

Done, please review.
